services:
  ducks_api:
    build: .
    ports:
      - '4141:4141'
    environment:
      DATABASE_URL: postgres://postgres:postgres-admin@easypanel.saulojustiniano.site:5433/ducks_db?sslmode=disable
      JWT_SECRET: 59c976415abc0192ded7552b311600d6d1ba9a01765f027eef0d496399721782
    command: sh -c "npm run setup && npm run db && npm run seed && node dist/index.js"
    volumes:
      - .:/app

volumes:
  pgdata:
